import type { TraceEnvelope } from "@stategraph/inspect";

// Simulated checkout form trace — demonstrates all 11 trace event types.
export const DEMO_TRACE: TraceEnvelope = {
  schemaVersion: "1.0",
  sessionId: "demo-session-0001",
  machineId: "checkoutForm",
  actorId: "checkoutForm:actor",
  createdAt: 1735000000000,
  events: [
    {
      type: "@actor.started",
      seq: 1,
      ts: 0,
      actorId: "checkoutForm:actor",
      snapshot: {
        status: "active",
        value: "idle",
        configuration: ["checkoutForm.idle"],
        context: { step: 1, email: "", cardNumber: "", error: null },
        changed: true,
        event: { type: "@@INIT" },
        nextEvents: ["START"],
        firedTransitions: [],
        pendingEffects: [],
        children: {},
        error: undefined,
        _traceId: "checkoutForm:actor:0",
      },
    },
    {
      type: "@event.received",
      seq: 2,
      ts: 245,
      actorId: "checkoutForm:actor",
      event: { type: "START" },
    },
    {
      type: "@transition.fired",
      seq: 3,
      ts: 246,
      actorId: "checkoutForm:actor",
      source: "checkoutForm.idle",
      target: "checkoutForm.filling",
      eventType: "START",
      guardResults: {},
    },
    {
      type: "@action.executed",
      seq: 4,
      ts: 246,
      actorId: "checkoutForm:actor",
      actionType: "clearError",
      params: undefined,
    },
    {
      type: "@event.received",
      seq: 5,
      ts: 1120,
      actorId: "checkoutForm:actor",
      event: { type: "UPDATE_FIELD", field: "email", value: "user@example.com" },
    },
    {
      type: "@transition.fired",
      seq: 6,
      ts: 1121,
      actorId: "checkoutForm:actor",
      source: "checkoutForm.filling",
      target: null,
      eventType: "UPDATE_FIELD",
      guardResults: {},
    },
    {
      type: "@context.updated",
      seq: 7,
      ts: 1121,
      actorId: "checkoutForm:actor",
      patch: { email: "user@example.com" },
    },
    {
      type: "@event.received",
      seq: 8,
      ts: 2304,
      actorId: "checkoutForm:actor",
      event: { type: "UPDATE_FIELD", field: "cardNumber", value: "4242 4242 4242 4242" },
    },
    {
      type: "@transition.fired",
      seq: 9,
      ts: 2305,
      actorId: "checkoutForm:actor",
      source: "checkoutForm.filling",
      target: null,
      eventType: "UPDATE_FIELD",
      guardResults: {},
    },
    {
      type: "@context.updated",
      seq: 10,
      ts: 2305,
      actorId: "checkoutForm:actor",
      patch: { cardNumber: "4242 4242 4242 4242" },
    },
    {
      type: "@event.received",
      seq: 11,
      ts: 3001,
      actorId: "checkoutForm:actor",
      event: { type: "SUBMIT" },
    },
    {
      type: "@transition.fired",
      seq: 12,
      ts: 3002,
      actorId: "checkoutForm:actor",
      source: "checkoutForm.filling",
      target: "checkoutForm.submitting",
      eventType: "SUBMIT",
      guardResults: { isFormValid: true },
    },
    {
      type: "@effect.started",
      seq: 13,
      ts: 3003,
      actorId: "checkoutForm:actor",
      effectId: "submitOrder:1",
      src: "submitOrder",
      input: { email: "user@example.com", cardNumber: "4242 4242 4242 4242" },
    },
    {
      type: "@effect.done",
      seq: 14,
      ts: 3841,
      actorId: "checkoutForm:actor",
      effectId: "submitOrder:1",
      output: { orderId: "ord_7x3p9q2r", amount: 99.99 },
    },
    {
      type: "@transition.fired",
      seq: 15,
      ts: 3842,
      actorId: "checkoutForm:actor",
      source: "checkoutForm.submitting",
      target: "checkoutForm.success",
      eventType: "done.invoke.submitOrder:1",
      guardResults: {},
    },
    {
      type: "@context.updated",
      seq: 16,
      ts: 3843,
      actorId: "checkoutForm:actor",
      patch: { orderId: "ord_7x3p9q2r" },
    },
    {
      type: "@actor.stopped",
      seq: 17,
      ts: 5000,
      actorId: "checkoutForm:actor",
    },
  ],
};
